### ISSUE TITLE
I am unable to set message code on edit text 

### ISSUE THREAD

**Issue by anilthakur** [stfalcon-studio/SmsVerifyCatcher#1]
I  have download project and run this project then i am unable to get callback on 

 smsVerifyCatcher = new SmsVerifyCatcher(this, new OnSmsCatchListener<String>() {
            @Override
            public void onSmsCatch(String message) {
                String code =parseCode(message);//Parse verification code
                etCode.setText(code);//set code in edit text

```
            Toast.makeText(MainActivity.this,"click",Toast.LENGTH_LONG).show();
            //then you can send verification code to server
        }
    }); please tell where am doing wrong any more thing we have to set?
```

**Comment by bevzaanton** [comment]
You have to set phone number filter, which comes with SMS
In sample project I set:
```
smsVerifyCatcher.setPhoneNumberFilter("777");
```
Are you sending SMS from phone number: 777?

**Comment by cyberformed** [comment]
not working at all. application is unable to catch the message also
