### ISSUE TITLE
Just a query

### ISSUE THREAD

**Issue by ShrikantBadwaik-007** [stfalcon-studio/SmsVerifyCatcher#11]
Hi, amazing library. Though I just have a question. How do i get only 4/5 digit code from any message irrespective of its content. Also i didn't understood below statement:
`Pattern p = Pattern.compile("\\b\\d{4}\\b");`
Thanks.

**Comment by yp25** [comment]
\\b\\d{4}\\b is regex pattern

\\b will searching any word boundary
\\d will search any digit numeric, short of 0-9
\\d{4} will search 4 digit numeric character

Please find more information here
https://www.javatpoint.com/java-regex

**Comment by ShrikantBadwaik-007** [comment]
ok thanks
