### ISSUE TITLE
Failed to compile in Android Studio 3.0, gradle plugin 3.0.0

### ISSUE THREAD

**Issue by GoltsevEugene** [stfalcon-studio/SmsVerifyCatcher#12]
Hi, it gives an error:
startup failed: build file '/Users/eugene.goltsev/code/goTap-Android/app/build.gradle': 98: expecting ''', found '\n' @ line 98, column 57. falcon:smsverifycatcher:0.3.1’

**Comment by abhay222** [comment]
Can you paste complete logs. As I am also using this Library in Android Studio 3.0 and Gradle 3.0.0. Its working fine for me.

**Comment by GoltsevEugene** [comment]
Wooow, I'm really sorry.
There is wrong text in ReadMe in description.

Current:
compile 'com.github.stfalcon:smsverifycatcher:0.3.1’
Should be:
compile 'com.github.stfalcon:smsverifycatcher:0.3.1'

Ending single quote is wrong.

**Comment by abhay222** [comment]
Now I remember this error, at the time of implementation I also got the same error. I have already submitted the pull request for it. But they haven't merged it.

**Comment by bevzaanton** [comment]
Merged: 
https://github.com/stfalcon-studio/SmsVerifyCatcher/pull/10
