### ISSUE TITLE
Misconfiguration of AndroidManifest.xml

### ISSUE THREAD

**Issue by blumfontein** [stfalcon-studio/SmsVerifyCatcher#16]
Hello!

Could you remove from your AndroidManifest.xml lines inside application tag:

android:allowBackup="true"
android:label="@string/app_name"
android:supportsRtl="true"

These lines are autogenerated by Android Studio, and not required for android modules. Their presence leads to conflicts, when I try to redefine these options in my AndroidManifest.xml. So I need to do some weird workaround.

Thank you

**Comment by bevzaanton** [comment]
Thanks @blumfontein ! I have fixed it.
