### ISSUE TITLE
SMS Permissions now not allowed in Android.My application got removed from playstore because of those permissions. Any new version from your side?

### ISSUE THREAD

**Issue by gvsharma** [stfalcon-studio/SmsVerifyCatcher#26]

**Comment by raquezha** [comment]
this library will not work anymore. you need to implement a server that will generate a hash that you will get. 

Read [more](https://developers.google.com/identity/sms-retriever/verify).
Detailed article [here](https://proandroiddev.com/no-more-sms-call-log-permissions-now-what-9b8226de7827)

**Comment by gvsharma** [comment]
thank you so much
