### ISSUE TITLE
Service Not Register

### ISSUE THREAD

**Issue by PratapRaj056** [stfalcon-studio/SmsVerifyCatcher#6]
When a user decline the permission request during start of the application, and when user decline the permission, SmsVerifyCatcher.onStart() is not run as permission is not granted. And in SmsVerifyCatcher onStart(), it is defined that register service when permission granted but omStop() there is no such condition, which is resulting in an exception.

**Comment by bevzaanton** [comment]
Hi, @PratapRaj056 ! 
Thanks for the interest in my library. Yes, you are right. It was a bug. 
I have fixed it in version 0.3.1. Please update your gradle dependency:
compile 'com.github.stfalcon:smsverifycatcher:0.3.1’

**Comment by PratapRaj056** [comment]
thanks a lot.
